# Descomentar y agregar lo necesario a generar en el compose
#version: '3.5'
#services:
#  redis:
#    image: "redis:alpine"
#    command: redis-server --requirepass rediscoopeuch
#    container_name: redis_local
#    ports:
#      - "6379:6379"
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: root
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
